### ISSUE TITLE
Properly attribute any third-party code we use

### ISSUE THREAD

**Issue by rkneufeld** [pedestal/pedestal#117]
**As a** project
**In order to** be responsible
**We need to** properly attribute third-party code Pedestal utilizes in a [NOTICES](../blob/master/NOTICES) file.

@sumbach and @brentonashworth have been noted as having info on this.

**Comment by mtnygard** [comment]
@rkneufeld "cors/src/blob.html" seems to have disappeared sometime since this issue was filed.

template-server/resources/public/enlive-template.html is still there, but I can't find any antecedent for that file. Are you sure that came from another project and is covered under a third-party license?

Similar question for mustache-template.html.

**Comment by mtnygard** [comment]
Most of the other files referenced by @sumbach are gone with the sunset of pedestal-app. Recommend we close this issue.

**Comment by sumbach** [comment]
@mtnygard I agree that this concern is largely (if not entirely) resolved with the removal of pedestal-app.

The only file left in the repo that leaves me with any concern is [samples/server-sent-events/resources/public/js/app.js](https://github.com/pedestal/pedestal/blob/master/samples/server-sent-events/resources/public/js/app.js).

**Comment by rkneufeld** [comment]
@mtnygard Agreed. The CORS example does now have one 3rd-party polyfill, referenced here: <https://github.com/pedestal/pedestal/tree/master/samples/cors#thanks>

**Comment by ohpauleez** [comment]
The server-sent-events app.js is written by me :)
