### ISSUE TITLE
Pedestal's out-of-the-box static file handling should include dir-index behavior by default 

### ISSUE THREAD

**Issue by chrisfjones** [pedestal/pedestal#259]
Dir-index behavior is described here: http://en.wikipedia.org/wiki/Webserver_directory_index
The gist of it is that a request to ```/my-dir/``` or ```/my-dir``` will redirect internally to ```/my-dir/index.html```
Nearly every web server provides this behavior by default (apache, nginx, tomcat, python simplehttpserver, etc). In order to get this behavior in pedestal today, you'd have to implement your own interceptor and wrap it at the appropriate level (http://stackoverflow.com/questions/7729628/serve-index-html-at-by-default-in-compojure). This issue proposes that dir-index behavior be included in pedestal's static file handling logic (i.e. the stuff configured via :io.pedestal.service.http/resource-path).

**Comment by mtnygard** [comment]
@ohpauleez Is this a reasonable time to move from using Ring's resource middleware to a Pedestal-native interceptor? I'd be willing to take on that work.

**Comment by ohpauleez** [comment]
@mtnygard Yeah, I'd merge a new interceptor that takes the place of Ring's resource middleware.  We should use NIO in the interceptor.

**Comment by ohpauleez** [comment]
This capability should be present in the default `file` interceptor.  Additionally, the new `fast-resource` interceptor also supports `index?` and other options.  The fast-interceptor optimizes responses based on the HTTP Buffer size.
If the file fits in the HTTP buffer, it'll one-shot it, otherwise, it'll async the response all the way to wire.

The new `fast-resource` is not a default interceptor, because it requires you to be on a platform that supports NIO responses.

**Comment by sergeiudris** [comment]
- it seems `fast-resource` `index?` option is ignored (5.8.0), opened https://github.com/pedestal/pedestal/issues/679
