### ISSUE TITLE
pedestal.immutant does not perform routing properly

### ISSUE THREAD

**Issue by piranha** [pedestal/pedestal#323]
If you:

- run `lein new pedestal-service qwe`
- go to `project.clj` and uncomment `pedestal.immutant`
- in `service.clj` change `::bootstrap/type` to `:immutant`

then `curl http://localhost:8080/about` returns `Not Found`. 

With `:jetty` it works as intended.

**Comment by ohpauleez** [comment]
I just updated the dependencies and did a quick triage.  This bug is confirmed and I'm not sure when the regression entered the source tree.  I originally thought it might be due to the changing Immutant API, but I couldn't find a quick way to confirm that.  I don't think Pedestal servlet integration has changed since the original immutant work.

Patches welcome.  cc/ @jcrossley3

**Comment by jcrossley3** [comment]
I'll take a look

**Comment by jcrossley3** [comment]
I'm only able to reproduce this with the latest release of Pedestal, 0.3.1. If I build from HEAD locally and pass `--snapshot` to `lein new ...`, it appears to work correctly. Am I doing it wrong? :)

**Comment by jcrossley3** [comment]
A simple workaround is to insert `[org.immutant/web "2.0.0-beta2"]` above `[io.pedestal/pedestal.immutant "0.3.1"]` in your `project.clj`

**Comment by jcrossley3** [comment]
This may just be a dupe of #291 which I believe was discovered/addressed post 0.3.1

**Comment by piranha** [comment]
Yeah, it's duplicate. Sorry, somehow missed previous one when I was searching for an issue! Adding dep to `[org.immutant/web "2.0.0-beta"]` fixes everything.

**Comment by ohpauleez** [comment]
Hmm, weird - I was definitely able to recreate with everything on master.  Maybe I had something mucking with my environment.  Thanks for hashing out the details @jcrossley3 - I really appreciate it!
