### ISSUE TITLE
Real world examples

### ISSUE THREAD

**Issue by kirillsalykin** [pedestal/pedestal#329]
It would be great if you can add links to real world (open source of course) example. 
Properly structured, with validation, database access. 

Also, it will be great to find examples of db migrations handling (especially datomic), something similar to rake tasks, some infrastructure for deployment.

This definitely will make life easier.

Thanks!

**Comment by kristianmandrup** [comment]
Why would Datomic use Db migrations!? That is so old school. Datomic is completely versioned (migrations are just diffs over time anyways). In Datomic the data contains the schema as I understand it, just like in Clojure, the program is data as well...

**Comment by JulianLeviston** [comment]
This is an interesting question that I also grappled with at the beginning with how to satisfy common requirements when building a web app.

 @kirillsalykin while it doesn't use pedestal, grateful place can answer many of your concerns and questions about schema versioning. One thing datomic's fully versioned approach caters for that "standard rails-style database schema migrations" doesn't is later down the track when you start to have issues where data relies on structure. (ie the "content" has certain "shape" reliances). Datomic naturally solves this by its intrinsic nature. https://github.com/flyingmachine/gratefulplace Having said this, you should definitely study Datomic and Datalog more, because it's quite deep.

@kristianmandrup while I understand your position, there is a need for separating the versioning of the structure of a database from its data, especially as development takes place... perhaps one has a staging application and two or so dev systems, with different features being developed in tandem... One needs a way to address these "different versions of the application having different database needs". Migrations provide a way to upgrade between arbitrary versions, especially if one is guided to write the migrations in a commutative way. Specification and keeping of as much of the history as is required to allow all the "versions of the deployed software in existence" is a necessary requirement of building an application in this way (the requirements of which don't magically go away because they're so "oldschool"). Having some kind of "story" or "answer" for pedestal's users in this regard is probably a good idea. It's a difficult problem, and requires some care.

Thankfully the amount of work required to build a migrations system is pretty small, so one can pretty much roll one's own once one understands all the requirements. This is, however, the difficult part.

**Comment by kirillsalykin** [comment]
@kristianmandrup @JulianLeviston thanks for the answers!

This looks like needed tool: https://github.com/rkneufeld/conformity.

I'll look on  https://github.com/flyingmachine/gratefulplace. Thanks for this example!

**Comment by kirillsalykin** [comment]
@kristianmandrup @JulianLeviston also i have a question about deployment infrastructure - are there any capistrano/mina (ruby world) similar things?

**Comment by JulianLeviston** [comment]
@kirillsalykin it's advisable to do some research. This isn't a help forum. http://lmgtfy.com/?q=capistrano+for+clojure

https://github.com/celestial-ops/supernal

**Comment by kirillsalykin** [comment]
@JulianLeviston :)

Right, sorry.

**Comment by kristianmandrup** [comment]
@kirillsalykin - a lot has happened in the tech world since the happy ROR days (2009-2012). For deployment, it is common to use Docker these days... For Datomic since it runs on JVM I would assume you would otherwise need whatever deployment too is most common in the Java/JVM world?

https://devcenter.heroku.com/articles/deploying-java-applications-with-the-heroku-maven-plugin
http://blogs.atlassian.com/2013/06/deploy-java-apps-with-docker-awesome/

Wauw, supernal sure looks awesome!

**Comment by ohpauleez** [comment]
Closing out this issue.  Feel free to move this over to the mailing-list for more discussion!
