### ISSUE TITLE
Interceptor lifecycle management

### ISSUE THREAD

**Issue by arohner** [pedestal/pedestal#335]
In our app, there are some interceptors with associated resources that need to be started & stopped when the pedestal app starts & stops. (threads, DB connections, etc). This is especially a problem during testing, because we create a new instance of the pedestal service during most tests, and failing to cleanup can cause resource leaks, and non-deterministic test failures. 

I would like a way to manage the lifecycle of our interceptors. 

One solution that comes to mind is to borrow the concept of stuartsierra/component, and add an optional :start and :stop key to (defrecord Interceptor), then during `io.pedestal.http/start` & `io.pedestal.http/stop`, call any attached :start & :stop fns. Another option is the same general approach, but to use Component directly, but bypass the system stuff, because interceptors already have an explicit dependency list.  

I'm happy to provide a PR with this behavior. Thoughts?

**Comment by ohpauleez** [comment]
Hi Allen - thanks for always volunteering to jump in and illustrate your ideas with PRs.  That attitude is very much appreciated.

I want to spend some time getting my head wrapped around the issue.  I have a few questions:
 * Are the interceptors truly the owners of the resources in question?
 * Should the resources ideally be passed into the interceptors (using a `defn`, previously `definterceptorfn`)?
 * In all cases where you'd like to use something like `:start`, where does a `defn` fall short and why?
 * Does this need only happen in testing, or is there another concern where something like a lifecycle would solve a problem?
 * Is the crux of the problem mostly around leaking resources - ie: no way to free resources or have `:stop` like functionality?
 * Have you considered a single interceptor near the base of your interceptor chain that manages all resources for the chain?  That single interceptor could be made to respect the `:start` and `:stop` lifecycle.

**Comment by arohner** [comment]
Bullet points out of order:

> Are the interceptors truly the owners of the resources in question?

Yes. These are resources that are never used or visible outside of the interceptor. 

> Is the crux of the problem mostly around leaking resources - ie: no way to free resources or have :stop like functionality?

Yes. 

> Does this need only happen in testing, or is there another concern where something like a lifecycle would solve a problem?

For now, testing is the main concern. Down the line, having a lifecycle makes hot-reloading of the app possible. Reloading being not possible because of resource leaks. 

> In all cases where you'd like to use something like :start, where does a defn fall short and why?

Defn could replace `:start`, but it felt symmetric with `:stop`.

> Should the resources ideally be passed into the interceptors (using a defn, previously definterceptorfn)?


Not really. It's a separation of concerns issue. For example, one interceptor's implementation uses a thread running that monitors requests that pass through. That thread is currently being started inside the defn, but passing the thread in from the outside would be at the wrong level.

> Have you considered a single interceptor near the base of your interceptor chain that manages all resources for the chain? That single interceptor could be made to respect the :start and :stop lifecycle.

I have a workaround at the app-level. Since Interceptor is a defrecord, I can assoc extra fields onto the record, and interceptors just provide :start and :stop. The main annoyance is that there is app-specific start & stop code that runs all of the interceptor `:start` & `:stops` , in addition to calling the official pedestal `io.pedestal.http/start` & `io.pedestal.http/stop`

**Comment by ohpauleez** [comment]
Your current work around is what I was going to suggest - you're building a system where you want a considerable amount of control around resource lifecycle, and you've made an architectural decision to couple that lifecycle with interceptors - otherwise, Interceptors are very (intentionally) stateless components.  In this approach, you're going beyond the expectations of Pedestal's limited lifecycle (start/stop on the main service) and you should feel comfortable subverting and controlling all notions of lifecycle for your service/needs.

In most instances that I can imagine (with the exception of the Thread instance you cited), the interceptor does not actually own the resource.  The resources are dedicated systems (for example, a database and connection pool), and it's advantageous for your system to introduce the resource into the service via an interceptor.

The Thread instance is interesting because choosing a dedicated Thread is a choice that is very fitting for production (you're only ever going to need one).  But architecturally speaking, if you were designing a system to be more modifiable or even robust in the event of teardown/restart, you'd just grab a thread off of an established thread pool (which would correctly expire the moment you destroyed all references to the original interceptor object).

It's unlikely that lifecycle management would be introduced into the Interceptor itself, but I am interested in any additional tooling, auxiliary functions, or adjusted function signatures that would make the use case easier.  Any thoughts here?

**Comment by ddeaguiar** [comment]
I don't think such an implementation or supported tooling belongs in Pedestal core. This need could be met by simply combining Pedestal with Component, for example. Alternatively, dependencies could be assoc'd to the service map, initialized as part of the service startup sequence and referenced by the requisite interceptors in the process.
