### ISSUE TITLE
Route conflict exception is raised

### ISSUE THREAD

**Issue by eunmin** [pedestal/pedestal#337]
Route conflict exception is raised in this code :

```clojure
(defroutes routes
  [[["/articles/:id/comments" {:get list-articles-comments}]
    ["/articles/:article-id/comments/:id" {:get view-article-comment}]]])

Exception in thread "main" clojure.lang.ExceptionInfo: route conflict ...
```

This raised by the `io.pedestal.http.route.prefix-tree/insert` function when meet a wildcard param in path spec.

Why specifically to handle with the wildcard param?

**Comment by ohpauleez** [comment]
Change the first route to `:article-id` instead of `:id` - does the exception still happen?

In the new default router, we build a prefix tree of all the routes.  At wildcards we need to branch, but the wildcard name must be a matched branch operation.  If you want the old router (and the old set of trade-offs), you can always set the `:router` setting in your service map.  Details are [in the pull request](https://github.com/pedestal/pedestal/pull/330)

**Comment by eunmin** [comment]
Rename the first route wildcard from :id to :article-id, Like this :
```clojure
(defroutes routes
  [[["/articles/:article-id/comments" {:get list-articles-comments}]
    ["/articles/:article-id/comments/:id" {:get view-article-comment}]]])

Exception in thread "main" clojure.lang.ExceptionInfo: route conflict ...
```
Works fine. Thanks for your answer. :)

**Comment by kroncatti** [comment]
Although the issue is resolved and it is easy to get around it by using the same wildcard, does it make sense to require the `wildcard` to be exactly the same when branching ?
