### ISSUE TITLE
Noisy logs when using a pedestal SSE

### ISSUE THREAD

**Issue by martintrojer** [pedestal/pedestal#359]
My logs are full of ERROR stack traces from here;
https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L105

This happens everytime a client closes an SSE connection and then either heartbeat or (my codes) data send fails. Its not really a ERROR in this case, more normal operation. 

In legacy pedestal you could try / catch these exceptions in your own code when calling send-event, see https://github.com/pedestal/docs/blob/master/documentation/service-sse.md

**Comment by martintrojer** [comment]
Related to #338

**Comment by daemianmack** [comment]
Are you just looking to squelch the log messages?

To that end, I'll typically do something like the following in my app's `config/logback.xml`...

```<logger name="io.pedestal.http.impl.servlet-interceptor" level="WARN" />```

**Comment by ohpauleez** [comment]
Hi @martintrojer - The ERRORs happen (mostly) because of newer Jetty + TCP Keepalive.  You can artificially generate a similar error if you do a standard HTTP request and close the browser before the response is finished sending.  As you pointed out, these errors aren't actually errors, but just log alerts that the connection broke at an unexpected time during its life cycle.

As mentioned in #338, Pedestal cleans up everything it creates, but if you store a reference to the event channel, that's your responsibility.  When Pedestal tears down SSE, it closes all channels.  If you put on a closed channel, the call will return `false` - the sentinel that you should clean up your reference.

If all you want to do is tune the logging, I would follow the advice from @daemianmack 

Does that answer your general concern/request?

**Comment by martintrojer** [comment]
Yes, tuning logback seems the way to go. Thanks for the tip

**Comment by martintrojer** [comment]
The correct logbook statement to turn these message off is

<logger name="io.pedestal.http.impl.servlet-interceptor" level="OFF"/>
