### ISSUE TITLE
Give a `leave` interceptor the opportunity to catch its own errors

### ISSUE THREAD

**Issue by frankiesardo** [pedestal/pedestal#360]
### Problem

An `enter` interceptor that throws an exception in its `enter` body has its own `error` body executed straight after. The same does not happen for a `leave` interceptor (the framework skips to the next interceptor).
### Rationale

A part from the inconsistent behaviour between enter and leave, this fix would be very useful for my case. In my library I provide interceptors that can potentially short circuit the execution and return an error response. My current implementation uses something like `if (error? result) (-> context terminate (assoc response ...)) (assoc context :request result)`.

However I want to leave the users the freedom to customise the error behaviour (and response). I can rewrite the interceptor to use the `:error` key.

``` clj
{:enter (fn ... (if (error? result) (throw (ex-data result)) (assoc  context request..))
 :error (fn ... (if I-threw-the-exception (assoc context :response..)}
```

Somebody who wants to override the error behaviour (or eliminate it) can simply assoc another `:error` fn to it. This works well for the enter case, but would not execute in the leave case.
### Proposed solution

Could be something as simple as changing the `leave-all-with-binding` function to do

``` clj
(let [..
       context (cond-> (assoc context ::stack (pop stack))
                        (complement ::error) (try-f interceptor :leave)
                        ::error (try-error interceptor))]
 ...)
```

But to be completely honest I don't understand some of the test failures.

**Comment by claj** [comment]
Why can't the user just stack the error-handling before your short-circuit-interceptor? It's easier than creating an error-handler that should handle both the enter and leave-cases, and using the router to compose the interceptors the user can stack as many error handlers before the short-circuiter as they want, as long as these error-handlers are selective in which exceptions they handle.

It feels a bit backward to compose the interceptors when defining them, rather than in the routing.

**Comment by ohpauleez** [comment]
@frankiesardo Is there a problem with providing two interceptors, one center only on functionality and one centered only on errors and messaging?

**Comment by frankiesardo** [comment]
@ohpauleez No there's no technical problem at all. The main issue is the unexpected inconsistent behaviour between `leave` and `enter` error handling, and the fact that instead of packaging behaviour+error handling in a single interceptor this functionality needs to be spread between two different interceptors.

But if you say to me this is working as expected or is not something you're inclined to change I can simply suggest to the users a more verbose solution.

**Comment by frankiesardo** [comment]
Now that I think of it I can actually rewrite my logic to encourage the use of pattern-matched error handling if that's what Pedestal is pushing for.

This is now just an issue about slightly different treatment of exceptions between enter and leave interceptors. Feel free to close it if you think it's not relevant anymore.

**Comment by ohpauleez** [comment]
Pedestal is definitely trying to encourage better error handling and the use of the pattern-matching exception handler.

I agree that the behavior differences between `enter`/`leave` and `error` seem odd.  Honestly, it's an implementation detail I've never stumbled upon because I typically write just functionality interceptors or just error interceptors (I rarely write an interceptor that bundles it all together).

I'm going to leave this issue open - I think we can improve the story a bit (even if that's just better documentation and expectation setting).

**Comment by hlship** [comment]
At time plus 7 years ... I'm afraid we're going to close this. I agree w/ Paul that a better pattern is an error handling interceptor and a functionality (enter and/or leave) interceptor.
