### ISSUE TITLE
[feature request] Extract router so it can be used also on client side

### ISSUE THREAD

**Issue by kirillsalykin** [pedestal/pedestal#374]
I do like pedestal router a lot (even it is terse :) ) and would like to use it on a client side (clojurescript).

Is it possible to extract it as a separate clojar? It would be awesome!

Thanks!

**Comment by frankiesardo** [comment]
This might be much more important than it looks. The favourite excuse for people not to use Pedestal is "because it's an all or nothing solution". Even if it conceptually remains the same, rewrite it as a composition of libraries can help adoption. 

The other obvious advantage is that it will be easier for people to port some part to Clojurescript or provide slightly different parsers experimenting new features (e.g. #278 )

**Comment by frankiesardo** [comment]
So I had some time during the holidays to write [tripod](https://github.com/frankiesardo/tripod).

This is obviously all very early stages and I'd really appreciate some feedback on it. 

It was not difficult to copy over the key concepts of pedestal and adapt them for cljs since it's mostly data manipulation.

It's basically just interceptors chain + route table but it's enough of a reason to start using this in ClojureScript and might convince people to try it in Ring and eventually migrate to Pedestal.

I believe there is room for a `pedestal/routing` library that just deals with routes and interceptor protocol and leaves to higher level libraries how to use this data structure to perform routing. There are two major concerns I've found while porting it from pedestal:
- How do we deal with verb maps? CLJS doesn't need them and strictly speaking they have nothing to do with routing. They are convenient, but it should be up to the handler to use something like Liberator to give the correct response for the method invoked. Pedestal generates a route with a name for each method, so it's quite a breaking change.

- CLJS has no eval. So I'm passing around a non quoted data structure. TBH I never fully understood why pedestal opted for a quoted route representation and manually evaluating interceptors expressions. Was it so you can persist the routing representation in something like edn format?

If we want to have an edn representation for the route table in CLJS one thing that could be interesting is to use keywords and multimethods. 

```clj
(defroutes routes
  [["/home" :foo/bar]]

(defmethod interceptor/enter :foo/bar [context] ...)

;; And then resolve
(extend-protocol IntoInterceptor
  clojure.lang.Keyword
  (-interceptor [t] (interceptor {:name t 
                                  :enter (get-method interceptor/enter t)
                                  :leave ..})))
```
But then it might be overkill/not what multimethods are supposed to be used for?

Anyway if you think `tripod` deserves a life on its own as a separate library, could you also advise on what's the best way to give credits to the pedestal team for all the code that I lifted?

**Comment by mavbozo** [comment]
@frankiesardo good job starting tripod :+1:

I tried using it in a very small cljs app and encounter error on uniqueness of route names.

My use case is 1 handler used by multiple slightly different pages for SEO A/B testing.

```
defroutes routes
  [["/" home]
   ["/info" info-page]
   ["/info-2" info-page]
   ["/info-3" info-page]
   ["/info-4" info-page]])
```

By looking at your code, I see that the name of the route is also the name of the handler. It would be nice to come up with a way to name each route uniquely even though they use same handler.

**Comment by frankiesardo** [comment]
Thanks for your feedback @mavbozo! Could you please repost your question as a tripod issue? I'm happy to start a discussion about this design decision but I fear this might not be the right place.

**Comment by ohpauleez** [comment]
This may happen around the 0.5.* release or the 1.0 release - it's unclear, but it is on our radar.  Excellent work on tripod @frankiesardo!

**Comment by frankiesardo** [comment]
Thanks Paul!

I'm happy that the pedestal team is planning to work on this. TBH implementing tripod was fun and it works well for all our cases (we have it in production on 3 big single page apps), but if more people were using it I expect maintaining all the edge cases would be too much for a person alone. Pedestal already has all the documentation, test tools and a consolidate code base to build upon.

I'm willing to contribute however I can for this to happen, even if it's just brainstorming ideas. On a side note, I know there is a [Google Group](https://groups.google.com/forum/#!forum/pedestal-users) for pedestal, but have you also considered hanging out in the [#slack](https://clojurians.slack.com/archives/pedestal) clojurians channel? It seems to be the preferred way to connect with the community for most projects (om, boot, datomic, etc.)

**Comment by ohpauleez** [comment]
Since the roadmap has tightened up a bit, it looks like this will happen in the 0.5.1 release, which will happen pretty shortly after the 0.5.0 release

**Comment by afhammad** [comment]
@ohpauleez this is great news. is the roadmap viewable somewhere? also is there a rough timeline for the releases?

**Comment by ohpauleez** [comment]
The roadmap is reflected in the tickets here on GitHub.  We just wrapped up a lot of work, so I need to go create the next group of tickets (and milestones).  0.5.0 will be released soon (sometime this week) and 0.5.1 should be released shortly after (within a few months).

0.5.1 will focus only on a few small tweaks, new sub projects (log, route, interceptor), new community pages on the GitHub Wiki, and a rewrite/refresh of the long-form documentation.  At this point, the APIs internal to Pedestal are stable, and now the docs can all be updated to reflect those.

**Comment by ohpauleez** [comment]
Log, Interceptor, and Route are their own modules on master now.  Enjoy!

**Comment by kirillsalykin** [comment]
awesome! thanks a lot for your work!
