### ISSUE TITLE
problem in accessing form-data.

### ISSUE THREAD

**Issue by shreyvithalani** [pedestal/pedestal#380]
I am not able to access form-data in pedestal.I am getting it as 
:form-params
 {"uname" "shrey",
  "__anti-forgery-token" "dZp1KkEsihnA4HhLw8zYFJxYns8a6kGU4PNo9wzsqjlZ5D4iKeCNPANr0s/NpNx5pn8NPZKUJUW9b+WM"} in request .when I pprint :form-params its showing {"uname" "shrey" ..}.when I am trying to get :uname its showing nil ,because its not in a proper map format.please help I am new to pedestal and clojure.Thank you!!

**Comment by terjesb** [comment]
Here the key is a string, not a keyword, so try getting "uname" instead of :uname.

Or you can maybe add the keyword-params interceptor and then get the keys from :params instead of :form-params. I think #240 plans to switch default to always use keywords for :params (but not change :form-params or :query-params).

**Comment by ohpauleez** [comment]
Hi @shreyvithalani - Thanks for giving Clojure and Pedestal a try!  Welcome!

@terjesb is correct, form-params are strings, not keywords.  Try to get "uname" instead of `:uname`

**Comment by shreyvithalani** [comment]
Thank you @terjesb @ohpauleez for your helpful comments.
