### ISSUE TITLE
Should dev-interceptors log exception?

### ISSUE THREAD

**Issue by jonpither** [pedestal/pedestal#391]
It went against expectation to see adding dev-interceptors stopped the exception being logged (unless I've misconfigured).

**Comment by ohpauleez** [comment]
Hi Jon, Thanks for using Pedestal and sorry you hit this hiccup!

dev-interceptors does not stop logging.  Perhaps there's something else wrong in your interceptor chain, or a dependency you're using has registered a no-op logger.  Are you able to point me to a minimal reproduction case?

Also in the future, these kinds of user issues are best posted to the [mailinglist](https://groups.google.com/forum/#!forum/pedestal-users), since there's better traffic there.

**Comment by mtnygard** [comment]
@ohpauleez @jonpither Was this ever resolved? Can the issue be closed?

**Comment by ohpauleez** [comment]
I have a repro and I see the code that needs to change.  I think this is valuable -- the `error-debug` function (used inside the `exception-debug` interceptor should still log the exception, in addition to sending it as the response body.

**Comment by ohpauleez** [comment]
Hi @jonpither - This is on master now.

**Comment by jonpither** [comment]
Thanks :-)
