### ISSUE TITLE
Interceptor framework and ring compatibility

### ISSUE THREAD

**Issue by JakePi3** [pedestal/pedestal#419]
Although the interceptor framework has a lot of advantages over ring handlers, there is a huge potential gap when incorporating ring middleware, and also with the way the single context is passed around.

Implicitly, ring handlers have access to the request as it comes in and return a response. They modify the request as it makes its way down the chain and then modify the response as it makes its way back up.  It's important to note the request that ring handlers capture is the original request when the handler is entered.

Within pedestal, the context containing both the request and the response is pushed down the chain and back up.  Crucially, there are no restrictions on what can be modified.  More subtly, the request that interceptors see during the `:leave` stage has been modified by other downstream interceptors.

Some ring middleware can therefore never function correctly (or at least reliably) when wired in as interceptors.  For example, the head interceptor was (as of 4.1) done as a wrapped Ring handler, but it could not possibly work.  It's now been swapped to a more native implementation, but the underlying problem remains.

To dig into this particular case, the head middleware captures a head request, transforms it to a get, and then dissocs the :body from the response on the way back up.

When this is done with interceptors, the `:enter` function applies the transformation but by the time the `:leave` function is invoked, the context holds the transformed request and the head middleware does not have the information it needs to drop the `:body`

There are tradeoffs here to be discussed.

One option to fix this ring incompatibility is for the interceptor framework to maintain a stack of requests and assoc the top of the stack into the context as each `:leave` function is about to be called.  This would allow each `:leave` function to see the same request as the corresponding `:enter` function in the same interceptor.

From a correctness point of view, this has some nice properties.

This is a breaking change, but I am interested in any discussion.

**Comment by claj** [comment]
I think I understand your points, although I think I prefer the interceptor model to Rings composed functions style most of the time.

The good news is that I'm not sure the change you propose must be a breaking one. One possible solution would be to add the incoming request on the interceptor in the interceptor stack when needed. You could pick up the original response for the :leave function when you're on your way back with a simple wrapper function accessing the interceptor queue/stack machinery.

The interceptor execution machinery implementation seem to be subject to some changes, but the idea of extending, yes even store data on, a certain interceptor item would probably be quite a stable feature. Maybe one could place the incoming request as meta-data on the interceptor? It is indeed a weird place to put data, but in this particular case it would be quite convenient to be able to access both the original and the modified request.

**Comment by JakePi3** [comment]
I agree with you that the interceptor model is superior.  This is what I've come up with to work ring incompatibilities:

```clojure
(defn push-req [context]
  (update-in context [:history :request] #(conj (or % []) (:request context))))

(defn peek-req [context]
  (peek (get-in context [:history :request])))

(defn pop-req [context]
  (update-in context [:history :request] pop))

(defn swap-req [context]
  (let [historical-request (peek-req context)]
    (-> context
        pop-req
        push-req
        (assoc :request historical-request))))
```

However, this requires manual pushing and popping of the state, relies on developers not making mistakes, and is not resilient against dynamic changes in the interceptor chain as the request is being serviced.  Not all interceptors implement both enter and leave functions so there is room for optimization as well. That's why I think it's a good candidate to pushing this inside the framework.

Ideally, the saved context would be associated with the interceptor itself so that the leave function could access state saved by the enter function.  The metadata is an interesting place to put it, and would satisfy this requirement. I had been thinking of an associative structure, or possibly even replacing the leave function dynamically by associng a curried 2-arity version with the saved context/request as the first parameter.

**Comment by ohpauleez** [comment]
I just wanted to comment quickly to let you both know I've seen this and I've been thinking about it.

The interceptor chain and lower-level details have been moving around a bit for the 0.5.0 release.  The four major changes taking place are:
 * Chains can now operate in different modes: `in`, `out`, or `in/out`.  The base chain operates in `in/out`, aka request/reply, just like it always did.  This change allows you to use interceptor chains for one-directional streams.
 * Pedestal no longer forces the base of the chain to be Servlet specific.  Instead, there is a "Chain Provider" that negotiates the connection from a lower-level container to the chain.  This allows Pedestal to sit on *any* container.  This opens up the ability to write high-performance containers for Pedestal.
 * There is an on-going investigation into the best data structure to use for the Context's queue and stack.  The current implementation is performant, but can thrash the GC a little.  The goal would be to use something more space and time efficient (since the chain is used for *every* request).
 * Pedestal will embrace the container where possible going forward.  The first candidate here is zero-copy request/response data structures.  This idea is at odds the Ring Spec, so it's still an open investigation into how much this will impact existing codebases.

The last point directly impacts the issue of middlewares and closed-over base requests.

**Comment by ohpauleez** [comment]
Given the changes made for 0.5.0 and the advice in this ticket thread (add another key in the context to track history), I'm going to close it out.  Thanks for the thoughtful issue, analysis, and conversation.
