### ISSUE TITLE
Docs: Clarify interceptor attachment within HTTP verbs map.

### ISSUE THREAD

**Issue by rauhs** [pedestal/pedestal#432]
Hi and thanks for making Pedestal.

I just made this silly mistake in a terse definition:

```
["/object/user/schemas/:user-id"
       {:get  xy
        :post [check-xy handler-xy]}]
```

Because I mixed up the definition of the `route-table` and the terse syntax. I thought that my `check-xy` interceptor gets called and then my handler. The worst here was that there was not a single error message and only my interceptor was called and never my handler which was quite confusing.

I found the proper syntax only in the tests:

```
["/object/user/schemas/:user-id"
       {:get  xy
        :post [:foo
               ^interceptors [check-xy]
               handler-xy]}]
```

Which is never mentioned in the docs.

1. Can this be added so that others don't stumble on this?
2. Shouldn't the terse syntax macro expansion complain about `check-xy` not being a keyword in my erroneous definition?

**Comment by rauhs** [comment]
Slightly unrelated:

In `routing-terse-syntax.md` the interceptors are usually "attached" before http-verb map `{:get ... :post ...}` but at the very end it's afterwards:

```
(defroutes routes
  [[["/order" {:get o/list-orders
               :post [:make-an-order o/create-order]}
              ^:interceptors [verify-request]
     ["/:id" {:get o/view-order
              :put o/update-order}
             ^:interceptors [o/verify-order-ownership
                             o/load-order-from-db]]]]])
```

is there a difference?

**Comment by ohpauleez** [comment]
Hi @rauhs -- thanks for using Pedestal and reporting the inconsistencies!

There will be a large documentation refresh following the 0.5.0 release (which will happen soon).
While we improved the error reporting with the terse format, there are still "gotchas" that sneak up on users (even me).  The advice that I tell everyone is always, "Just take a look at the tests - everything you can do, all configuration options, are in the tests.  That's where I go when I forget."

I understand that's a terrible answer - we're working to make the docs better.
- - - - 

The position of the interceptors vector doesn't matter - it can come before or after verb-map, it's purely a style thing.

In the original vision of the terse format, it was designed that "before the verb map, applied interceptors to the verb map and everything after it; After the verb map only applied interceptors to routes that followed/nested after the verb map."  That vision was never realized because it can lead to subtle behavior differences in your application that are hard to quickly identify in the code.
