### ISSUE TITLE
:context-path not in 0.5.0?

### ISSUE THREAD

**Issue by terjesb** [pedestal/pedestal#439]
I have an app deployed to WildFly 10/Immutant 2 that works on some 0.4.2-SNAPSHOT and stops working on 0.5.0. It relies on req :context-path from the container.

I noticed that io.pedestal.http.request.map now has these commented out:

```
;(assoc! :servlet-context (.getServletContext ^ServletConfig servlet))
;(assoc! :context-path (.getContextPath servlet-req))
;(assoc! :servlet-path (.getServletPath servlet-req))
```

What's the recommended migration here?

**Comment by ohpauleez** [comment]
Hi @terjesb, thanks for the report (and for trying 0.5.0 out before the announcement)!  I was hoping a few people would try it out to sort out these issues before it got announced more publicly.

With the creation on Chain Providers, the request got more generic (dropping the servlet specific pieces), exposing only a single function for servlet-related request creation.  Those pieces were tentatively going to be removed (because you could always get to them from `:servlet`, `:servlet-request`, and `:servlet-response` -- Just saving space and time per request for the common case.

Are you looking at the `:context-path` directly in your application?  If so, you should replace that code with something like `(some-> (:servlet-request response) (.getContextPath))`?  Is the application failing [in routing](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/route.clj#L180-L194) -- maybe because you're using `url-for` or the sequential router or passing your own function for routing?

**Comment by terjesb** [comment]
Thanks, @ohpauleez. So great seeing Pedestal move forward! I'm currently using :context-path via a locally patched version of propan/geheimtur (auth for Pedestal; looking forward to seeing what bits Arachne will use/provide in that area) in order to get proper login-uri routing on WildFly.

So shouldn't be a problem to add your replacement there. Haven't used url-for yet, but hopefully those pieces will also somehow work on servlet containers going forward? (Btw, also posted a table-routes question to the mailing list.)

**Comment by ohpauleez** [comment]
As part of the 0.5.1 effort, we're gll loooing to start pulling community projects (and community-powered documentation) more into the fold, which should help situations like this.  `url-for` should work as expected unless a developer is manually doing something interesting with the context's request.  Nonetheless, keep me posted as things pop up, and I'll ensure things move forward nicely for you!

**Comment by ohpauleez** [comment]
Report back here once everything works out as expected and we'll close out the issue.

**Comment by terjesb** [comment]
Great, that fixes it. :servlet-request is attached to both context and request, so can be used from both interceptors and simple request handlers.
