### ISSUE TITLE
Allow body-params default parser-map to handle multipart requests

### ISSUE THREAD

**Issue by dball** [pedestal/pedestal#444]
There doesn't seem to be any good reason that multipart uploads aren't handled out of the box by body-params, particularly when this stanza seems to do the trick:

```
(assoc (body-params/default-parser-map)
       #"^multipart/form-data;"
       (fn [request]
         (ring.middleware.multipart-params/multipart-params-request
          request {:store identity}))))
```

I'd be happy to thread in multipart parser options, add this, and provide test coverage if you're interested in including it.

**Comment by ohpauleez** [comment]
Hi @dball -- thanks for using Pedestal and filing this idea!

Currently, multipart uploads would only be handled if you included the multipart interceptor, but since multipart uploads happen through a standard POST call like a form-post, logically, they should happen in body-params (after all, they are called "multipart params").

Let me think about this some more, but thanks for documenting it.

**Comment by ohpauleez** [comment]
Thanks again for submitting the issue/idea!

Given that multipart params are usually used for file uploads (in which case, the `:store` option has significant importance), and there's already an interceptor to handle multipart uploads, I'm not inclined to have the core `body-params` take on all that additional work.  But as you illustrated, you're free to control the part however you like.

For those that stumble on this issue, it's advised that multipart requests get handled by a dedicated interceptor.
