### ISSUE TITLE
Var and Symbol implementations of IntoInterceptor should provide a name

### ISSUE THREAD

**Issue by mtnygard** [pedestal/pedestal#463]
# Description

If we continue to support vars and symbols in interceptor position in routing syntaxes, they should supply the interceptor name from the var or symbol.

## Expected Behavior

This should be a sufficient routing table:

    (def routes
      #{["/greet" :get #'respond-hello]})

## Actual Behavior

Exception results:

```
java.lang.AssertionError: Assert failed: In row 1, the last interceptor does not have a name and there is no explicit :route-name.
The whole route was: ["/greet" :get #'front-page/respond-hello]
default-route-name
```

I have no idea where the "default-route-name" bit comes from.

## Steps to reproduce

Repro case:

```
(ns front-page
  (:require [io.pedestal.http :as http]
            [io.pedestal.http.route :as route]))

(defn respond-hello [_]
  {:status 200 :body "Hello, world!"})

(def routes
  #{["/greet" :get #'respond-hello]})
```

# Environment

## Operating System (including version).

N/A

## Your current Leiningen version (`lein --version`)

N/A

## Pedestal version

0.5.1

**Comment by ohpauleez** [comment]
The restriction on interceptor names exists only in routes, as it's needed for `url-for`.  The other route definitions/formats enforce this in preprocessing.  The other definitions stand on the verbose-map processor, which [includes Interceptor name shaping](https://github.com/pedestal/pedestal/blob/master/route/src/io/pedestal/http/route/definition/verbose.clj#L20).

Interceptor names aren't required because it's possible to generate anonymous interceptors on-the-fly for client-specific request handling.

This issue should be fixed directly in the table routes processing.  Also note, this problem doesn't exist if you syntax quote the entire table route data structure, or of you syntax quote the endpoint functions, as done in the service template (the issue only occurs if you use Vars for handlers).

**Comment by mtnygard** [comment]
If I understand you correctly then, we should make the table syntax use the same Interceptor name shaping? If so, I can tackle that.

I'm slightly surprised by that though, since IntoInterceptor is extended to named things... why wouldn't we do the name shaping right there instead of having it come externally from the syntax processor?

**Comment by ohpauleez** [comment]
A var or a symbol could resolve to anything (not just a function), which in turn would be transformed into an interceptor (eg. a map, another interceptor, something else you defined).

The `:name` constraint only exists in route definitions, and only to power `url-for`.  Allowing that to influence the processing path/assumptions made at the base level (IntoInterceptor) seemed far reaching and overly aggressive.  IntoInterceptor is only concerned with one thing - turning something/anything into an interceptor that can be executed on a chain - and it achieves that.

**Comment by ohpauleez** [comment]
This is where [the table route preprocesses names](https://github.com/pedestal/pedestal/blob/master/route/src/io/pedestal/http/route/definition/table.clj#L86)

**Comment by mtnygard** [comment]
OK, I understand the objectives better now.

**Comment by mtnygard** [comment]
I'm inclined to close this issue rather than attempting to rewrite it to apply to the table routes.

**Comment by ohpauleez** [comment]
I agree -- note that the table routes preprocessor already handles symbols and one should prefer symbols to vars as handlers in Pedestal route definitions.

**Comment by ddeaguiar** [comment]
So I was not aware of this preference. I'm accustomed to using interceptors created through `io.pedestal.interceptor/interceptor` as handlers. This is definitely good docs material.

**Comment by ohpauleez** [comment]
@ddeaguiar Anything that conforms to the interceptor API can be used anywhere within your routes.  There's no need to ensure your handler is already an interceptor.
