### ISSUE TITLE
Doc issue: clarification of setting :response in an intercepter

### ISSUE THREAD

**Issue by deg** [pedestal/pedestal#511]
I was recently bitten by lack of knowledge, writing an interceptor for a Vase app.

I needed to set the context's `:response` and then let it be processed by existing Vase code (e.g., converting the response to transit).

I initially did this in the `:enter` of my interceptor, and was surprised to discover that the remaining interceptors were not called. (The proximate reason is https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L373, and I assume that the intention is deliberate).

It was easy to fix my code; I just needed to set the response in my `:leave`. But, this was not obvious at first, and would be helped by more documentation and examples of how to write interceptors. (Ideally, also with a link to this part of the Pedestal docs from the Vase docs).

**Comment by deg** [comment]
Whoops, I should have filed this in pedestal-docs.

**Comment by ohpauleez** [comment]
I believe this is well documented in the [Pedestal docs](http://pedestal.io/reference/interceptors) and covered in various other channels, like my recent [Clojure/West talk on Pedestal and Vase](https://www.youtube.com/watch?v=_Cf-STRvFy8).

In the context, there is a sequence of `:terminators`, predicate functions that determine if processing is complete or not.  The default terminator for all HTTP application is the presence of a `:response` in the context - Once there is a response, the system should send it immediately.  When processing stops because of a terminator, the leave stage is called for all interceptors on the stack (ie: all interceptors that have already been called/processed via `:enter`).

Your interceptor should still be called on the `:enter` stage, it just needs to be placed later in the queue (so your other interceptors can also have a chance to perform their processing).

**Comment by deg** [comment]
Oops, we crossed paths. I moved this issue to pedestal-docs and closed this issue, while you were answering here.

Before I give a longer answer... your call: should we re-open and continue here, or move this discussion to pedestal-docs?

**Comment by ohpauleez** [comment]
Hi @deg - let's just move the conversation over to `pedestal-docs`.  Thanks for following up!
