### ISSUE TITLE
Problem in routing

### ISSUE THREAD

**Issue by ikitommi** [pedestal/pedestal#532]
# Description

A wildcard route masks non-wildcard routes with prefix-tree router.

## Expected Behavior

Route should match.

## Actual Behavior

Does not.

## Steps to reproduce

```clj
(require '[io.pedestal.http.route.definition.table :as table])
(require '[io.pedestal.http.route.map-tree :as map-tree])
(require '[io.pedestal.http.route.router :as router])

(router/find-route
  (map-tree/router
    (table/table-routes
      [["/:a" :get (constantly "") :route-name ::ping]
       ["/evil/ping" :get (constantly "") :route-name ::evil-ping]]))
  {:path-info "/evil/ping" :request-method :get})
; => nil
```

# Environment

```clj
[io.pedestal/pedestal.service       "0.5.2"]
```

**Comment by terjesb** [comment]
My understanding of http://pedestal.io/reference/routing-quick-reference is that this is intentional: 'wildcard routes always win over explicit paths in the same subtree'. A wildcard route at the root wins over everything else. I suspect you might need to implement the wildcard via a fallback through a custom not-found interceptor instead.

**Comment by ikitommi** [comment]
Thanks foe the quick reply. I would assume that because the wildcard-route has only one path segment, it would be ignored here (the request `:path-info` has 2) and thus would not mask the static route.

**Comment by ohpauleez** [comment]
Hi @ikitommi,
Thanks for using Pedestal and reaching out with your issue.  The behavior you're describing is intentional (as mentioned in the docs).  Wildcard/Splat and URL-param routes always win over explicit paths.  I often suggest that users consider using query-string args instead of URL-param routes -- more optimizations can be applied in the route table when all the routes are "static"
In addition to the doc site, you can find more details on the routing behavior in the prefix tree mentioned in the [0.5.0 release notes](https://github.com/pedestal/pedestal/releases/tag/0.5.0) and the trade-offs explained in the [prefix tree pull request](https://github.com/pedestal/pedestal/pull/330).

If you want to use Wildcard/Splat and URL-param routes and still match on explicit paths, you can use the `:linear` router.

Post here if you have any more questions!

**Comment by ikitommi** [comment]
Thanks for the reply. I don't agree on how it should work, but understand your point. Cheers.

**Comment by ikitommi** [comment]
Hi. I did a custom version of the prefix-router, that solves this by walking all potential paths if one ends in a dead-end. Also rewrote the internals with reified Protocols, it's 4x faster in micro benchmarks. Need some testing still, but could/should this be back-ported to Pedestal?

* https://github.com/metosin/reitit/pull/44
* https://stackoverflow.com/questions/45271346/trie-implementation-with-wildcard-values

**Comment by ohpauleez** [comment]
Hi @ikitommi 
Thanks for digging in and great to see you invest the effort!

I'll do my best to do a deep dive into the code sometime this week.  After a quick pass though, you've made a handful of changes I've mentioned to @mtnygard - combine map-tree and prefix into a single data structure, change the map implementation for faster lookups (you might consider using Java 8's [Collections.unmodifiableMap](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#unmodifiableMap-java.util.Map-) instead of HashMap).

Does your router also apply constraints?  If not, that could also be adding to the 300-1000ns that Pedestal is using.

I'd love to see a conversation here to see if folks want to re-enable the wildcard handling in the prefix-tree router.

**Comment by ikitommi** [comment]
thanks for the quick reply.

In `reitit`, all the route (meta-)data is accumulated into leafs, which can be used to do route constraints (e.g. ring-router uses this to enforce on the `:http-request`), but no guards for selecting if a path should be matched in the first place. So, by design, it does much less than the Pedestal router and thus the direct perf comparisons might not be fair.

Still, I think the internal `lookup` should be directly comparable(?), running 1000 route matches on a route tree is 2.3ms with Pedestal ja 0.8ms after polishing => 2.5+x faster. Only difference is at the moment, that if multiple routes have an exact match, only the last payload is used. This is because `reitit` runs full route conflict resolution for all routes, so there shouldn't be any duplicate routes. If this would be back-ported to Pedestal, it should be changed so that the payloads for multiple routes are accumulated as it does now.

Good point about the `Collections.unmodifiableMap`. In this case, the `HashMap` is only visible into the `Router` body via a closure, so it should be safe. Also, HashMap does one function call less , so it's SO MUCH faster ;)

**Comment by ikitommi** [comment]
Hi. I noticed that my modified version of the `prefix-tree` was still broken: it (or the Pedestal prefix-tree-router) can't handle paths like this:

```clj
[["/:kikka"]
 ["/:kukka/ping"]
 ["/api/users/"]]
```
, which are in no conflict. Started to redo the router from scratch, issue linked. Lookup is now 4x faster than the Pedestal impl and it's only 50 loc. Will add the catch-all handling and tests. As you have done more routing stuff, would appreciate feedback. And happy to PR this back to Pedestal when done.

**Comment by kirillsalykin** [comment]
@ikitommi thank you for your work!

Quick question, would it be possible to implement `constraints` as a function which accepts `context` returns `true` or `false`.

So, it won't be just regexp.

eg like 
```
[["/kikka" :constraints #(= (get-in % [:request :name]) "test"]]
```

**Comment by ikitommi** [comment]
Hi. There aren't any constraints in the routing lib I'm building (it's a standalone _simple_ routing lib, outside of Pedestal), so someone from the Pedestal team should answer how the constraints should work in the future with pedestal-routes. I have never used them.

**Comment by ohpauleez** [comment]
@ikitommi I just saw your updated comments now - sorry for the extremely late reply (I was dealing with a family issue around the time of the comments).

Constraints are only used to reject a match, not produce a match.  I would have to refresh my memory a bit, but I believe they can return anything truthy to pass.  Currently, [the code](https://github.com/pedestal/pedestal/blob/master/route/src/io/pedestal/http/route/prefix_tree.clj#L451) expects regular expressions, but we could make that polymorphic via a protocol.

Regardless, great work with retit and the other metosin projects.  I have some ideas about better Pedestal integration and ecosystem stuff I'd love to run by you sometime.

**Comment by ikitommi** [comment]
thanks and looking forward to the ecosystem stuff.

But those who would like to check pedestal+reitit per today, here's a guide: https://cljdoc.org/d/metosin/reitit/0.2.10/doc/http/pedestal (without the constraints, not likely to add those, there is parameter coercion to validate the params, invalid params cause error, not reject a match)
