### ISSUE TITLE
Rename `negotiate-content` function

### ISSUE THREAD

**Issue by cloojure** [pedestal/pedestal#545]
# Description
As with #542, this issue seeks to improve naming.

The function `negotiate-content` **_does not_** "negotiate content". Rather, it returns an interceptor that will perform content negotiation for incoming requests.  As such, a better name would be something like the following (in order of increasing brevity):

 - generate-content-negotiation-interceptor
 - gen-content-negotiation-interceptor
 - content-negotiator

Or, since the namespace is pretty small, perhaps just:

 - io.pedestal.http.content-negotiation/interceptor      ; returns an interceptor

There are probably other functions and/or namespaces that could be improved, if viewed through  a fresh set of eyes. Just as it is very difficult to proofread one's own writing, it is easier for a newcomer to Pedestal to notice confusing, inconsistent, or conflicting names.

## Pedestal version
0.5.3

**Comment by ohpauleez** [comment]
It's common in Pedestal for functions that return Interceptors to be named for their final artifact (eg: The function that returns a content-negotiation Interceptor is named `negotiate-content`).  This is because these functions are Interceptor Builders, parameterizing the creation of the Interceptor itself.

When using these functions in your route table, their intent becomes clear.  The docstring is also clear about the contract of the function.
