### ISSUE TITLE
Correctly handle nil values in :headers map when using io.pedestal.test/response-for

### ISSUE THREAD

**Issue by kennyjwilli** [pedestal/pedestal#554]
# Description
Calling `response-for` with `nil` as a header value will result in an exception being logged as an ERROR. The error message is not thrown in the REPL. Additionally, an incorrect response map is returned.

## Expected Behavior
`nil` values in the `:headers` map are handled gracefully with no exception thrown. The correct response map is returned.

## Actual Behavior
[This exception](https://pastebin.com/P6A0Pm9S) is thrown in the logs when called with a nil header value (see below steps). Also an incorrect response map is returned: 

```clojure
{:status nil, :body "", :headers nil}
```

## Steps to reproduce

```clojure
(io.pedestal.test/response-for
  service-fn
  :post "/my-route"
  :headers {"cookie" nil})
=> {:status nil, :body "", :headers nil}
```

This exception is caused by the elements array passed to `String/join` being `null` [here](https://github.com/pedestal/pedestal/blob/e9230c3a49b7036b195267c7c24b0c4881c941b5/service/src/io/pedestal/http/request.clj#L27). `(enumeration-seq (.getHeaders servlet-req key))` is null.

## Pedestal version
`[io.pedestal/pedestal.service "0.5.3"]`

**Comment by ohpauleez** [comment]
Hi @kennyjwilli - thanks for reporting the issue!

Is your expectation that `nil` should work because of your experience elsewhere (ie: another web library, testing tool, or live traffic against a Pedestal web application)?  A nil value doesn't conform to the [Ring Spec](https://github.com/ring-clojure/ring/blob/master/SPEC).

What is your expectation about how `nil` header values should be gracefully handled?  How should a `nil` value be interrupted?

Given that it doesn't conform to the spec, I'd expect an exception to be thrown, but in this case, was the exception not informative?

**Comment by kennyjwilli** [comment]
Given that it does not conform to the Ring Spec, I'd also expect an exception to be thrown. The exception linked above is rather obtuse, however; it's not at all clear that the issue is because my `:headers` map contains a `nil` value. I think a better approach would be to throw as soon as we know the `:headers` map does not pass the spec, rather than throwing when `String/join` is passed `nil`.

**Comment by mtnygard** [comment]
@ohpauleez I asked @kennyjwilli to submit an issue when I saw his questions on Slack. He got a stack trace that started in stylobate. I don't think we should ask users to understand stylobate or depend on its implementation.

**Comment by ohpauleez** [comment]
Totally agree on all counts.  I think an exception should occur and I think it should happen early in processing (in a similar style to how we process Interceptors now).  If anyone takes this ticket, the fix is to add an additional assert at the start of processing headers.  Care needs to be given not to make this assert in the core function for processing headers (which is performance critical and potentially used on other Chain Providers which rather the behavior stay the same.

**Comment by ohpauleez** [comment]
This fix is now on master.  Thanks for reporting!
