### ISSUE TITLE
Suggestion: *out*/*err* -friendly logging adapters

### ISSUE THREAD

**Issue by vemv** [pedestal/pedestal#571]
Hi!

I perceive a need in pedestal.log, let me know what you think:

Say I'm developing a library, which should be logger-agnostic in order to target all kind of developers (Pedestal users, Timbre users, 12-Factor App followers etc). Therefore a sensitive choice seems to just println to `*out*` and `*err*`, which are made configurable by the library.

Now, imagine I want to use that library from a Pedestal project. Then I should configure its `*out*`/`*err*` bindings with something analog to:

```
(reify java.io.Writer
  (write [...]
    (io.pedestal.log/error ...)))
```

...that way, all kind of logging (from the example library, and from the consuming project) would use the same exact implementation, which is clearly desirable.

Now, this `reify` seems easy to implement. Following CONTRIBUTING.md, I'm asking you first if this sounds like a good idea.

Thanks - Victor

**Comment by ohpauleez** [comment]
Hi!  Thanks for taking the time to pull your idea together and present it!

Let me briefly walk through some of the pieces that make up Pedestal's logging support before we dive into your idea.

SLF4J is usually the API/Facade that most logging backend development against on the JVM.  `io.pedestal.log` develops against this API, letting developers decide exactly what their logging backend/implementation should be.  In addition, Pedestal's logging goes further, allowing developers to program directly to the logging protocols.

Pedestal's logging setup also supports circumventing it via environment variables set on start-up (for example, if you want to completely disable logs, or if you want to redirect all logging to a different subsystem/backend based on environment).

The combination of these three things (SLf4J support, logging protocols, setting logging based on environment variables), means that most development and deployment schemes are easy to achieve.

I think your suggested feature is best tackled in application code, because there isn't a common default that would be suitable for everyone (some systems pick up STDOUT/ERR and redirect to syslog, some systems redirect to logging backends, some systems want to leave it untouched).
For your specific use case, you could either reify the interfaces, extend the logging protocols, or use another library that plumbs STDOUT/ERR to SLF4J.

I'm going to close this issue, but please feel free to continue the discussion!

**Comment by vemv** [comment]
Thanks for the detailed reply @ohpauleez ! I'm gonna reflect on it when I have the chance.
