### ISSUE TITLE
Easier handling of Character Encoding / Content-Length

### ISSUE THREAD

**Issue by orestis** [pedestal/pedestal#582]
# Description

First of all, thanks for all the hard work for creating and maintaining Pedestal. I'm having tons of fun :)

I'm a relatively newcomer to Clojure and the JVM, and after trying to setup a simple HTTP JSON API on top of Pedestal, I was surprised to find that this is not there out of the box, nor there are samples to show how to handle them — and googling doesn't seem to help either. I fixed my immediate use case, but I'm filing an issue after discussion on Slack.

Imagine an API that returns a JSON object. I expect the final HTTP response to be encoded in UTF-8, and a correct Content-Length header to be added. Following the [Hello world with content types](http://pedestal.io/guides/hello-world-content-types) I can see how I can convert a hash map to JSON, using the library of my choice. However, it's not at all clear from the documentation when an where the `String` that most JSON libraries provide gets turned into bytes, and how I can tap into this.

I've managed to come up with this on my own:

```
(def coerce-to-json
  {:name ::coerce-to-json
   :leave
   (fn [context]
     (let [response         (get context :response)
           body             (get response :body)
           coerced-body     (.getBytes (json/generate-string body) StandardCharsets/UTF_8)
           updated-headers  (assoc (get response :headers {})
                                   "Content-Type" "application/json"
                                    "Content-Length" (str (count coerced-body)))
           updated-response (assoc response
                                   :headers updated-headers
                                   :body    coerced-body)]
       (assoc context :response updated-response)))})
```

But I would really expect that there would be a default interceptor that does both of those out of the box — having an out of the box Content Length working is hugely important. I realise this might be a Ring issue, since I couldn't find *anything* on this. I've tested this in Jetty but I'm not sure how it would look like under other servers.

## Expected Behavior

An Example on how to serve JSON using a built-in interceptor that took care of the low-level details would be nice :) 

## Pedestal version

0.5.4

**Comment by mk** [comment]
Hi @orestis,

There's the json-body interceptor in pedestal that does just that:
https://github.com/pedestal/pedestal/blob/09dd88c4ce7f89c7fbb7a398077eb970b3785d2d/service/src/io/pedestal/http.clj#L115-L127

To use it, you set the response body to a collection type and make sure the json-body interceptor comes afterwards in your interceptor chain. You can also enqueue it dynamically like so:

```clojure
(require '[io.pedestal.interceptor.chain :as chain]
         '[io.pedestal.http :as http])

(def my-api-interceptor
  {:name ::api
   :enter
   (fn [context]
     (-> context
         (assoc-in [:response :body] {"my-api" "data"})
         (chain/enqueue http/json-body)))})
```

Hope this helps!

**Comment by orestis** [comment]
Hi, many thanks for your reply — I've seen this interceptor, but unless I'm missing something, it doesn't address `Content-Length` at all, and it still passes a `String` (not a `byte[]`) to the underlying server/container. Sorry if my original issue was too verbose!

**Comment by mk** [comment]
Ah sorry I missed that. I guess the built-in json-body interceptor is more about streaming so it avoids having to compute the length upfront.

**Comment by orestis** [comment]
Ah right, it even avoids doing the transformation and instead passing in a function to the body. Does it make sense to have an eager version of that in Pedestal? Or perhaps having an example in the Guide would suffice?

**Comment by ohpauleez** [comment]
Hi @orestis - thanks for the kind words and thanks for using Pedestal!

Sorry you've seemed to hit a snag!  In the future, you might also consider reaching out on the [Pedestal Mailing List](https://groups.google.com/forum/#!forum/pedestal-users) for issues like this (there's a wider audience there than here).

Most of Pedestal's response-oriented utilities support streaming operations (including `json-body`), which can make "Content-Length" difficult to know, because the stream may be lazily generated.  These utilities tend to be very narrowly focused (they only do/touch the response content, not the entire response 'object').

I've created a new [json-api sample](https://github.com/pedestal/pedestal/tree/json-api-sample/samples/json-api) that shows how to correctly use `json-body` as well as write a custom version of `json-body` that can be application-specific.  Check out the [service.clj](https://github.com/pedestal/pedestal/blob/json-api-sample/samples/json-api/src/json_api/service.clj) file and the tests.

Hope this helps!

**Comment by orestis** [comment]
Thanks! I'm still not sure how UTF-8 is guaranteed — looking at what I think is the [relevant code](https://github.com/pedestal/pedestal/blob/fdb79ee8c473ec7a222a212fd8e8538f2d0cc592/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L52), the `OutputStreamWriter` is not passed in an explicit `Charset` — therefore the "platform default encoding" is used according to the docs. I think an explicit charset for Strings make sense?

**Comment by ohpauleez** [comment]
Since the string is created via [JSON generation/encoding](https://github.com/dakrone/cheshire#encoding), character encoding gets enforced at that level.

At `servlet-interceptor` you're at the lowest point in the Pedestal stack, right before you hand control back to the container to put your response on the wire.

**Comment by orestis** [comment]
Thanks @ohpauleez, I've moved this discussion to the mailing list [here](https://groups.google.com/forum/#!topic/pedestal-users/mNniRquHQ4o) — I may be very well much mistaken but I just can't drop this just yet :)
