### ISSUE TITLE
Change build from Leiningen to deps.edn

### ISSUE THREAD

**Issue by kommen** [pedestal/pedestal#595]
Clojure tools.deps supports coordinates of dependencies from git repositories. Pedestal however doesn't provide the necessary `deps.edn` files.

A current use case would be to use a version of pedestal compatible with Clojure 1.10-beta1. It needs this fix: https://github.com/pedestal/pedestal/commit/64b8f877590c8bb66341544728da576d8e33124f

Without tools.deps support and without having a current SNAPSHOT of pedestal available, giving the Clojure beta a try is a PITA.

**Comment by ddeaguiar** [comment]
@kommen while I can see getting `deps.edn` support on the roadmap the supporting tooling is still alpha and it's currently unclear as to how it will impact the current tooling landscape (i.e., lein) and we have yet to hash it's adoption. I'd be hesitant to drop in `deps.edn` files into each project because we'd end up with multiple sources of truth regarding project dependencies which have the potential to become out of sync.

That being said, the core issue is the defect you referred to which is blocking the use of the current release. While there are many ways that this can be addressed, I'll explore the possibility of cutting a release which includes the fix.

**Comment by ddeaguiar** [comment]
@kommen actually, we'll look into dropping `deps.edn` files into each project. I had a conversation with @ohpauleez about this and he's recommended an approach which should satisfy our current tooling needs while maintaining a single source of truth for deps.

**Comment by hlship** [comment]
This is already been implemented as part of 0.6.0.
