### ISSUE TITLE
Option to set max header size

### ISSUE THREAD

**Issue by wilkerlucio** [pedestal/pedestal#615]
# Description

Currently, there is no straight forward way to define the max header size while running the local server. After some discussion in #clojure we end up with this current solution (as part of the server configuration):

```clojure
(defn set-request-header-size [x max-size]
  (->> x
       (.getServer)
       (.getConnectors)
       (mapcat #(.getConnectionFactories %))
       (filter #(instance? org.eclipse.jetty.server.HttpConnectionFactory %))
       (run! (fn [factory]
               (-> factory
                   (.getHttpConfiguration)
                   (.setRequestHeaderSize max-size))))))

(def server
  {:io.pedestal.http/container-options {:context-configurator #(set-request-header-size % 500000)}})
```

## Expected Behavior

Pedestal could provide some flag we can send to the server to directly set, without having to manually traverse the HTTP classes.

**Comment by ohpauleez** [comment]
This doesn't seem so bad to me personally (and it's what I'd encourage anyone else to do).  It has always been the stance of the project to allow users to have full control over the platform.

That said, there are a handful of options related to the create of the HTTP Configuration that's passed to all the connection factories.  We ought to consider allowing someone to pass in the HTTP Configuration object under a key for cases like this (allowing someone to control the entire HTTP Conf instead of per-option after the fact).  We might prefix the key to denote that it's jetty specific.
See https://github.com/pedestal/pedestal/blob/master/jetty/src/io/pedestal/http/jetty.clj#L113 for more info.

**Comment by ddeaguiar** [comment]
Released with `0.5.6`.

**Comment by wilkerlucio** [comment]
@ddeaguiar hello, thanks for this, but can you clarify what was changed about this? I tried tracking the changelog and commits but didn't get it clear.

**Comment by ddeaguiar** [comment]
@wilkerlucio, sorry that it's not clear. I'll work on clarifying the documentation. In the meantime, you can provide your own HttpConfiguration instance via the :io.pedestal.http.jetty/http-configuration container option ([code](https://github.com/pedestal/pedestal/blob/86afc33bd8b40d77de224a8a73834abd0ab76349/jetty/src/io/pedestal/http/jetty.clj#L114-L116)).

**Comment by ddeaguiar** [comment]
@wilkerlucio, here's how you can set the request header size now (superfluous code elided):

```
(ns my.service
  (:require [io.pedestal.http :as http]
            [io.pedestal.http.route :as route]
            [io.pedestal.http.body-params :as body-params]
            [ring.util.response :as ring-resp])
  (:import (org.eclipse.jetty.server HttpConfiguration)))

...

(defn http-configuration
  [max-size]
  (doto (HttpConfiguration.)
    (.setRequestHeaderSize max-size)))

(def service {:env :prod
              ...
              ;; Options to pass to the container (Jetty)
              ::http/container-options {;; You can specify you're own Jetty HTTPConfiguration
                                        ;; via the `:io.pedestal.http.jetty/http-configuration` container option.
                                        :io.pedestal.http.jetty/http-configuration (http-configuration 5000)
                                        }})
```
