### ISSUE TITLE
Xray tracing causes ClassCastException if no xray headers in request

### ISSUE THREAD

**Issue by ordnungswidrig** [pedestal/pedestal#617]
# Description

I observed this exception when running an application outside of AWS, e.g. locally on my machine:

```
Caused by: java.lang.ClassCastException: io.opentracing.noop.NoopSpanImpl cannot be cast to com.amazonaws.xray.entities.Entity
	at io.pedestal.log.aws.xray$eval5768$span_resolver__5769.invoke(form-init6841701985794906378.clj:201)
	at io.pedestal.interceptor.trace$tracing_interceptor$fn__18230.invoke(trace.clj:98)
	at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:54)
	... 39 common frames omitted
```

A first analysis shows that this [line in `span-resolver`](https://github.com/pedestal/pedestal/blob/master/aws/src/io/pedestal/log/aws/xray.clj#L230) returns a `NoopSpanImpl` which is excpected to be an Entity in line #258

## Expected Behavior

Xray tracing either reports a proper error if run outside of AWS or does gracefully falls back to something else.

## Actual Behavior

ClasspathException as descibed above

## Steps to reproduce

Use pedestal-aws 0.5.5 outside of AWS like this:

````clojure
(ns ...
   (:require
      [io.pedestal.interceptor.trace :as trace]
      [io.pedestal.log.aws.xray :as xray]
      ...))
 

(def tracing-interceptor (trace/tracing-interceptor {:span-resolver xray/span-resolver
                                                     :span-postprocess xray/span-postprocess}))
````

# Environment

## Operating System (including version).

Any outside of a real AWS environment

## Pedestal version

0.5.5

**Comment by ohpauleez** [comment]
Hi @ordnungswidrig,
Thanks for the issue report!
Two quick questions:  Are you running an X-Ray agent locally (either from [installing](https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-ec2.html) one or using [a docker setup](https://github.com/pedestal/pedestal/tree/master/samples/tracing-interceptor-aws#running-a-distributed-trace-server))?  Are you setting the `PEDESTAL_TRACER` environment variable when you're running?

Along with those two questions, I assume you're following the steps in the [x-ray sample](https://github.com/pedestal/pedestal/tree/master/samples/tracing-interceptor-aws#running-a-distributed-trace-server).

- - - - - 

To clarify a bit, the x-ray tracing support expects that an agent is present and running.  If there isn't, it's expected to produce an error.  I typically recommend that tracing interceptors be conditionally added to the chain based on mode/environment (since tracing is inappropriate to have active during a test suite, for example).
That said, I think this should produce a more accurate error.

**Comment by ordnungswidrig** [comment]
@ohpauleez I was running an application which I was not familiar with and did no local xray / AWS setup. I didn't had `PEDESTAL_TRACER` set, but setting it to `io.pedestal.log.aws.xray/tracer` doesn't make a difference as one might expect.

The tracing interceptor is setup in code as described above and as you suggested it's perfectly valid for pedestal to raise an error in that case. But the actual error should not be a ClassCastException.

**Comment by ddeaguiar** [comment]
We could check whether `log/span` returns a `NoopSpan` and throw a more specific error. I'll look to see if there's a better alternative.

**Comment by ddeaguiar** [comment]
Catching the ClassCastException and returning a more informative error message.
