### ISSUE TITLE
Allow to customize the "default" logger

### ISSUE THREAD

**Issue by souenzzo** [pedestal/pedestal#666]
# Description

`io.pedestal.log` currently support to use custom formatted by parameter.

By default, it will fall into `pr-str` and it's not customizable.

- https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L271
- https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L289
- https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L391

## Expected Behavior

Should be possible to configure the logger formatter from java properties

like `-Dio.pedestal.log.default-formatter=my.custom.log/encoder`

If I'm running in AWS, i can format the output as JSON because CloudWatch can understand it

If I'm running on my machine, i can log as EDN because it's easier to read

## Actual Behavior

Logs are always printed with EDN, even when using an JSON logger appender.
```javascript
{"level": "INFO", "message": "{:msg \"GET /hello\", :line 20}" ...}
```

I need to create my custom log namespace per-project and handle that

## Pedestal version

0.6.0

**Comment by souenzzo** [comment]
Proposal:

define
```clojure
(def default-formatter
  (delay (or (some-> "io.pedestal.log.default-formatter"
                     System/getProperty
                     requiring-resolve)
             pr-str)))
```

and use `(::formatter ctx-map @default-formatter)` on both highlighted lines

**Comment by ddeaguiar** [comment]
Hi @souenzzo. Thanks for opening up this issue based on the discussions in the discussion in the Clojurians #pedestal Slack channel. I can understand the need since service developers must currently create their own log macros which specify the formatter explicitly. This, however, leaves Pedestal's internal logging untouched. By providing a formatting override we'd give service developers more control over logging.

I'd like to think through the implications of this further, though, as there are places internally where we log the entire context (primarily for the `DEBUG` level) which would need to be accounted for when considering an alternative formatter. There would at least need to be some indication to service developers as to what they are getting into.

As for the implementation, I'm leaning towards what is done for the `override-logger` ([here](https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L196-L199)). I'm not sure who still runs services on Clojure versions prior to 1.10 but I'd rather hold off on including `requiring-resolve` if we can avoid it.

**Comment by ohpauleez** [comment]
Food for thought-

There is nothing in Pedestal that prevents developers from taking deeper control of the logging facilities -- they can be packaged up in different functions, macros, and APIs.  Pedestal provides one such API on top of the core interfaces/protocols that is informed by the 'whole' of Pedestal (the macros being discussed).  The recommendation in the past has been to used the foundational pieces and shape an API that makes sense for your systems/applications (and that appears to be the case here).  This has been the recommendation because the primary building-block for logging APIs already supports different formatters (https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L271).  In fact, log messages can all include a `::formatter` that does the dynamic resolution described/desired (no need for an extra hook, but it does mean all your messages need to include it).

The default-logger is a "zero-cost" option -- there is no additional overhead incurred for supporting it, since it's a top-level, late-binded entity (eg: If you don't use it, there is no cost incurred by the user/system).  This is done because the logger is a required (but implicit) entity within the "logging system".
A formatter does not fit this heuristic (required, but implicit).

All that said, based on where the [formatter gets expanded](https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L280), we could possibly take an approach like `override-logger`, but never resolve the symbol (just put it in place).  Of course, this would be weird because the default used in other places _does_ require a resolved var.

Anyone else from the community want to chime in?  Is the logging formatter a pain point for others?  Do you have to work around it or does it cause you to incur a cost when building a system?  Have you always hoped it worked a different way?

**Comment by ohpauleez** [comment]
Food for thought-

There is nothing in Pedestal that prevents developers from taking deeper control of the logging facilities -- they can be packaged up in different functions, macros, and APIs.  Pedestal provides one such API on top of the core interfaces/protocols that is informed by the 'whole' of Pedestal (the macros being discussed).  The recommendation in the past has been to used the foundational pieces and shape an API that makes sense for your systems/applications (and that appears to be the case here).  This has been the recommendation because the primary building-block for logging APIs already supports different formatters (https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L271).  In fact, log messages can all include a `::formatter` that does the dynamic resolution described/desired (no need for an extra hook, but it does mean all your messages need to include it).

The default-logger is a "zero-cost" option -- there is no additional overhead incurred for supporting it, since it's a top-level, late-binded entity (eg: If you don't use it, there is no cost incurred by the user/system).  This is done because the logger is a required (but implicit) entity within the "logging system".
A formatter does not fit this heuristic (required, but implicit).

All that said, based on where the [formatter gets expanded](https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L280), we could possibly take an approach like `override-logger`, but never resolve the symbol (just put it in place).  Of course, this would be weird because the default used in other places _does_ require a resolved var.

Anyone else from the community want to chime in?  Is the logging formatter a pain point for others?  Do you have to work around it or does it cause you to incur a cost when building a system?  Have you always hoped it worked a different way?

**Comment by ddeaguiar** [comment]
For context, The Slack conversations which led to this issue can be found [here](https://clojurians-log.clojureverse.org/pedestal/2020-06-17) and [here](https://clojurians-log.clojureverse.org/pedestal/2020-06-20).

@ohpauleez as far as I know, there's no way to extend alternative log message formatting to the logging done by Pedestal's internals. That may be by design, although I don't have enough context to convey the rationale. But I do get the impression that when folks want to control formatting, they want to do so for all logs emitted by Pedestal Log.

**Comment by ohpauleez** [comment]
It would be my expectation that log formatting is bounded-context specific.  For example, I can't control the formatting of Jetty or Vertx logs, but I shouldn't expect to be able to do that (it's outside of my control domain) -- at best I could only turn on JSON-layout logging at the log configuration level (assuming my [logging backend supported that](https://logging.apache.org/log4j/log4j-2.2/manual/layouts.html)).

Related to Layout configuration -- @souenzzo Have you tried using a JSON Layout in your logging configuration?  If so, in what ways did not that meet you needs or expectations?

**Comment by ddeaguiar** [comment]
> It would be my expectation that log formatting is bounded-context specific. For example, I can't control the formatting of Jetty or Vertx logs, but I shouldn't expect to be able to do that (it's outside of my control domain)

@ohpauleez, yeah, I agree that the format of the log _message_ is bounded-context specific. I blurred the lines between log _message_ and _event_ and should be careful not to do so.

I do think what we're lacking here is an explicit problem statement and I think your questions are trying to uncover it.

**Comment by gnarroway** [comment]
@ohpauleez I did try a basic [json layout](https://logging.apache.org/log4j/2.x/manual/layouts.html) earlier with log4j2, and note that the main log being written is json (with attributes like the level, timestamp etc), the part that `io.pedestal.log` handles is all embedded in the "message" field as an edn string, which is hard to work with.

e.g.

```json
{"level": "INFO", "message": "{:msg \"GET /hello\", :line 20}"}
```

A built in solution to easily configure this would be very useful since the increasingly cloud-native world has a lot of facilities for handling json logs.

**Comment by gnarroway** [comment]
Using wrapper macros as discussed [on slack](https://clojurians-log.clojureverse.org/pedestal/2020-06-20) is workable but the line numbers are just `nil` from my test.

@ddeaguiar do you mind releasing #fcfdb6c753e4172e9fb81ebaed461adb007ff8ab since it missed 0.5.8? This will make using `io.pedestal.log/log` workable (currently it throws NPE) and we could use that instead. 

Alternatively if `io.pedestal.log/log-expr` was made public, it would be easier to just provide our own macros on top of that in a similar manner to the inbuilt ones, but with custom options. We can of course copy it into all our projects but that would be a bit smelly.

**Comment by ohpauleez** [comment]
Pedestal2 exposes log-expr as well as extensible formatting that can be controlled.

**Comment by PavlosMelissinos** [comment]
What's the status of this? I'm not sure if this matches the original question but I'll try to capture the problem statement that I'm seeing as of 2022-12-14 in a few words.

Users of pedestal should be able to specify a custom application-wide logger that will allow the appropriate logging implementation & appender to format the following log line:

```clojure
(io.pedestal.log/info :msg "GET /hello")
```
as
```JSON
{"level": "INFO", "msg": "GET /hello", :line 20}
```

As it stands now, it is formatted as such:
```JSON
{"level": "INFO", "message": "{:msg \"GET /hello\", :line 20}"}
```
The map is "swallowed" by pr-str into "message", so it becomes a plain string long before the logging implementation picks it up.

Apologies if there's already a solution but to be honest I haven't been able to find it.

**Comment by souenzzo** [comment]
@hlship can we bump this issue? 

I updated the description and examples.

A PR is welcome?

**Comment by hlship** [comment]
If you've signed the CLA, then I would be happy to look at a PR.  This is something needed inside NuBank as well.

**Comment by hlship** [comment]
I'm going to take a crack at this today.
