### ISSUE TITLE
Document how to use ring middlewares as interceptors

### ISSUE THREAD

**Issue by MIJOTHY-V2** [pedestal/pedestal#676]
The [readme](https://github.com/pedestal/pedestal#notable-capabilities) states one of the notable capabilities of pedestal is
> The ability to utilize Ring Middleware as Pedestal Interceptors

Does this apply to arbitrary ring middlewares? It would be useful to provide some examples if this applies to ring middleware. The closest I can see to this is the [handler](http://pedestal.io/reference/interceptors#_handlers) section in the documentation, but this doesn't explicitly reference ring. I may have missed something though.

For context, currently I have implemented a custom interceptor map to get the functionality of [`ring-logger`](https://github.com/nberger/ring-logger) in my app. The ideal situation would be just dropping `(ring-logger/wrap-with-logger my-app)` into the app, but I can't figure it out.

Cheers.

**Comment by ohpauleez** [comment]
Most Ring middleware split their functionality into two functions - one function that is applied to the request and another function that is applied to the response.  You can see that in ring-logger follows this pattern with [`wrap-log-request-start`](https://github.com/nberger/ring-logger/blob/master/src/ring/logger.clj#L62) and later wrap-log-response.

Turning this middleware into an interceptor is relatively straightforward - you would end up with an interceptor that called the `wrap-log-request-start` on `:enter` and `wrap-log-response` on `:leave`.

You can see how Pedestal internally converts different Ring middleware into Interceptors [here](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/ring_middlewares.clj).  You'll notice the use of various Interceptor helper functions (including the [`middleware`](https://github.com/pedestal/pedestal/blob/master/interceptor/src/io/pedestal/interceptor/helpers.clj#L289) helper) -- these are completely optional and in more recent Pedestal changes we have opted to just write out the interceptors as maps rather than use the helper functions.

**Comment by MIJOTHY-V2** [comment]
> Most Ring middleware split their functionality into two functions - one function that is applied to the request and another function that is applied to the response. You can see that in ring-logger follows this pattern with [`wrap-log-request-start`](https://github.com/nberger/ring-logger/blob/master/src/ring/logger.clj#L62) and later wrap-log-response.
> 
> Turning this middleware into an interceptor is relatively straightforward - you would end up with an interceptor that called the `wrap-log-request-start` on `:enter` and `wrap-log-response` on `:leave`.
> 
> You can see how Pedestal internally converts different Ring middleware into Interceptors [here](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/ring_middlewares.clj). You'll notice the use of various Interceptor helper functions (including the [`middleware`](https://github.com/pedestal/pedestal/blob/master/interceptor/src/io/pedestal/interceptor/helpers.clj#L289) helper) -- these are completely optional and in more recent Pedestal changes we have opted to just write out the interceptors as maps rather than use the helper functions.

Thanks for the quick response. This is along the lines of what I suspected, that in the general case there is some manual refactoring required rather than being able to drop in a middleware with an adapter.
