### ISSUE TITLE
HTTP Headers should be treated as case-insensitive

### ISSUE THREAD

**Issue by jacreynolds** [pedestal/pedestal#735]
# Description
HTTP RFC states that headers are not case sensitive, so when checking for the existence of headers, case should not matter.

## Expected Behavior
Returning a header with `content-type` should be recognized and no function for getting the default content type should be called.

## Actual Behavior
If the return headers key case does not match the expected case, the content type header is not recognized and a default content type function is called, potentially adding an additional content-type header.

## Steps to reproduce
Return from an interceptor a header using the unexpected case (all lowercase) content-type and a body of an async channel. Pedestal will throw an exception because there is no implementation of `default-content-type` for an async channel.

# Environment
All

## Operating System (including version).
All

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Recent tools/deps

## Pedestal version
https://github.com/pedestal/pedestal/blob/53bfe70143a22cdfd2f0d183023334a199c9e9a2/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L151

**Comment by hlship** [comment]
On entry, the incoming headers are all converted to lower case (see io.pedestal.http.request.servlet-support/servlet-request-headers).

I have now gathered that the issue is on the response map side; the [Ring Spec](https://github.com/ring-clojure/ring/blob/master/SPEC#L117) is not specific about handling of case, but the implemenation of Ring and Pedestal assumes you are using capitalized kebab case (e.g., "Content-Type" not "content-type") when setting _response_ headers.

This could be documented better (I can make that change) but since we are exposing a map value, rather than a method, there isn't a lot we can do about case insensitivity; if you want to write a utility function to look up in a case-insensitive way, that's on your code, but the rest of Pedestal (including code not maintained by the Pedestal team) can't be expected to change to support this.

["Be generous in what you accept, and specific in what you produce"](https://en.wikipedia.org/wiki/Robustness_principle) applies here .. we are generous is what we expect from the universe of potential clients, but are specific about what we expect code running in our process (in the Pedestal library, or in code from your application)  should provide.
